name: MADDOG
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - appnope=0.1.2=py38h50d1736_1
  - argon2-cffi=20.1.0=py38h5406a74_2
  - async_generator=1.10=py_0
  - atk-1.0=2.36.0=he69c4ee_4
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bioconductor-ggtree=2.4.0=r40_0
  - bioconductor-treeio=1.14.0=r40_0
  - biopython=1.78=py38h96a0964_2
  - bleach=3.3.0=pyh44b312d_0
  - boost-cpp=1.74.0=h43a636a_2
  - bwidget=1.9.14=h694c41f_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2021.5.30=h033912b_0
  - cairo=1.16.0=h4ec454a_1007
  - cctools_osx-64=949.0.1=h6407bdd_22
  - certifi=2021.5.30=py38h50d1736_0
  - cffi=1.14.4=py38h979bc6b_1
  - cfitsio=3.470=h01dc385_7
  - clang=11.0.1=h694c41f_1
  - clang-11=11.0.1=default_hf8bb9ca_1
  - clang_osx-64=11.0.1=hb91bd55_2
  - clangxx=11.0.1=default_hf8bb9ca_1
  - clangxx_osx-64=11.0.1=h7e1b574_2
  - compiler-rt=11.0.1=h654b07c_0
  - compiler-rt_osx-64=11.0.1=h8c5fa43_0
  - curl=7.71.1=hcb81553_8
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.10=h1c7c35f_0
  - ffmpeg=4.3.1=hb787a4c_2
  - fftw=3.3.9=nompi_h02cd531_101
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h10f422b_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.5=h0b31af3_1002
  - fribidi=1.0.10=hbcb3906_0
  - gdk-pixbuf=2.42.2=h976c81d_2
  - geos=3.9.1=he49afe7_2
  - geotiff=1.6.0=h4fce3c3_4
  - gettext=0.19.8.1=h7937167_1005
  - gfortran_impl_osx-64=9.3.0=h9cc0e5e_19
  - gfortran_osx-64=9.3.0=h18f7dce_14
  - ghostscript=9.53.3=h2e338ed_2
  - giflib=5.2.1=hbcb3906_2
  - git=2.30.1=pl5320hbb84d65_1
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - graphite2=1.3.13=h2e338ed_1001
  - graphviz=2.42.3=h055b950_2
  - gsl=2.6=h71c5fe9_2
  - gtk2=2.24.33=h55c0dba_0
  - gts=0.7.6=hccb3bdf_2
  - harfbuzz=2.7.4=hf28d55f_0
  - hdf4=4.2.13=h71d84a9_1004
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - imagemagick=7.0.10_62=pl5262h6797231_0
  - importlib-metadata=3.4.0=py38h50d1736_0
  - importlib_metadata=3.4.0=hd8ed1ab_0
  - ipykernel=5.4.2=py38h9bb44b7_0
  - ipython=7.20.0=py38h9bb44b7_2
  - ipython_genutils=0.2.0=py_1
  - iqtree=2.0.3=h7eed37d_1
  - isl=0.22.1=hb1e8313_2
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.0=py38h50d1736_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=hbcb3906_0
  - json-c=0.15=hcb556a6_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py38h50d1736_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kealib=1.4.14=ha0ce315_1
  - kiwisolver=1.3.1=py38hd9c93a9_1
  - krb5=1.17.2=h60d9502_0
  - lame=3.100=h35c211d_1001
  - lcms2=2.12=h577c468_0
  - ld64_osx-64=530=hea264c1_19
  - ldid=2.1.2=h7660a38_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang-cpp11=11.0.1=default_hf8bb9ca_1
  - libcurl=7.71.1=h9bf37e3_8
  - libcxx=11.0.1=habf9029_0
  - libdap4=3.20.6=h75eb3ff_1
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgcc=4.8.5=1
  - libgdal=3.1.4=h62a8350_8
  - libgfortran=5.0.0=9_3_0_h6c81a4c_22
  - libgfortran-devel_osx-64=9.3.0=h6c81a4c_22
  - libgfortran5=9.3.0=h6c81a4c_22
  - libglib=2.66.7=hd556434_1
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h3dc3bee_1012
  - liblapack=3.9.0=8_openblas
  - libllvm11=11.0.1=h223d4b2_0
  - libllvm12=12.0.0=hd011deb_1
  - libnetcdf=4.7.4=nompi_h9d8a93f_107
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.1=h052a64a_2
  - librsvg=2.50.3=hd4300c0_1
  - librttopo=1.1.0=h4e44bc7_6
  - libsodium=1.0.18=hbcb3906_1
  - libspatialite=5.0.1=h395434c_3
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.2.0=h355d032_0
  - libwebp=1.2.0=h1648767_0
  - libwebp-base=1.2.0=h0d85af4_2
  - libxcb=1.13=h35c211d_1003
  - libxml2=2.9.10=h93ec3fd_4
  - llvm-openmp=11.0.1=h7c73e74_0
  - llvm-tools=11.0.1=h223d4b2_0
  - lz4-c=1.9.3=h046ec9c_0
  - mafft=7.475=hb4d813b_1
  - make=4.3=h22f3db7_1
  - markupsafe=1.1.1=py38h5406a74_3
  - matplotlib-base=3.3.4=py38hb24f337_0
  - mistune=0.8.4=py38h5406a74_1003
  - mpc=1.1.0=ha57cd0f_1009
  - mpfr=4.0.2=h72d8aaf_1
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h50d1736_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nettle=3.6=hedd7734_0
  - notebook=6.2.0=py38h50d1736_0
  - numpy=1.20.1=py38h64deac9_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.4.0=h6cbf5cd_0
  - openssl=1.1.1l=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.2=py38hb77cc89_0
  - pandoc=2.11.4=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha86e081_5
  - parso=0.8.1=pyhd8ed1ab_0
  - pcre=8.44=hb1e8313_0
  - pcre2=10.36=h5cf9962_1
  - perl=5.26.2=hbcb3906_1008
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py38h4c06724_2
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pkg-config=0.29.2=h31203cd_1008
  - poppler=0.89.0=hd735947_5
  - poppler-data=0.4.10=0
  - postgresql=13.1=ha63e576_2
  - proj=7.2.0=h78d1473_2
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.4=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h5406a74_2
  - python=3.8.6=h624753d_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.0.1=py38hd5c72dd_0
  - r-ade4=1.7_16=r40hc2c5f09_1
  - r-adegenet=2.1.3=r40h28b5c78_1
  - r-adephylo=1.1_11=r40h28b5c78_3
  - r-animation=2.6=r40hc72bb7e_3
  - r-ape=5.4_1=r40hdfb1349_0
  - r-aplot=0.0.6=r40hc72bb7e_0
  - r-askpass=1.1=r40h28b5c78_2
  - r-assertthat=0.2.1=r40hc72bb7e_2
  - r-backports=1.2.1=r40h28b5c78_0
  - r-base=4.0.3=hc5a05b9_6
  - r-base64enc=0.1_3=r40h28b5c78_1004
  - r-biocmanager=1.30.10=r40h6115d3f_1
  - r-blob=1.2.1=r40hc72bb7e_1
  - r-boot=1.3_27=r40hc72bb7e_0
  - r-brew=1.0_6=r40hc72bb7e_1003
  - r-brio=1.1.1=r40h066c5db_0
  - r-broom=0.7.4=r40hc72bb7e_0
  - r-bslib=0.2.4=r40hc72bb7e_0
  - r-cachem=1.0.4=r40hf6ff476_0
  - r-callr=3.5.1=r40h142f84f_0
  - r-caper=1.0.1=r40hc72bb7e_1002
  - r-caret=6.0_86=r40h17f1fa6_2
  - r-cellranger=1.1.0=r40hc72bb7e_1003
  - r-class=7.3_18=r40h066c5db_0
  - r-classint=0.4_3=r40h749f5a1_2
  - r-cli=2.3.0=r40hc72bb7e_0
  - r-clipr=0.7.1=r40hc72bb7e_0
  - r-cluster=2.1.0=r40h1a6e9bf_4
  - r-clustergeneration=1.3.7=r40ha770c72_0
  - r-coda=0.19_4=r40hc72bb7e_0
  - r-codetools=0.2_18=r40hc72bb7e_0
  - r-colorspace=2.0_0=r40h6b199c2_0
  - r-combinat=0.0_8=r40hc72bb7e_1003
  - r-commonmark=1.7=r40h28b5c78_1002
  - r-covr=3.5.1=r40h710217c_0
  - r-cpp11=0.2.6=r40hc72bb7e_0
  - r-crayon=1.4.1=r40hc72bb7e_0
  - r-crosstalk=1.1.1=r40hc72bb7e_0
  - r-crul=1.0.0=r40h6115d3f_0
  - r-curl=4.3.2=r40h28b5c78_0
  - r-data.table=1.13.6=r40h066c5db_0
  - r-dbi=1.1.1=r40hc72bb7e_0
  - r-dbplyr=2.1.0=r40hc72bb7e_0
  - r-deldir=0.2_10=r40h749f5a1_0
  - r-desc=1.2.0=r40h6115d3f_1003
  - r-devtools=2.4.2=r40hc72bb7e_0
  - r-diffobj=0.3.3=r40h28b5c78_0
  - r-digest=0.6.27=r40h342fd00_0
  - r-dplyr=1.0.4=r40h4efb63e_0
  - r-dt=0.18=r40hc72bb7e_0
  - r-e1071=1.7_4=r40h342fd00_0
  - r-ellipsis=0.3.1=r40h17f1fa6_0
  - r-essentials=4.0=r40hd8ed1ab_2002
  - r-evaluate=0.14=r40hc72bb7e_2
  - r-expm=0.999_6=r40h30cbcce_0
  - r-fansi=0.4.2=r40h28b5c78_0
  - r-farver=2.0.3=r40hc5da6b9_1
  - r-fastmap=1.1.0=r40h815b84a_0
  - r-fastmatch=1.1_0=r40h28b5c78_1005
  - r-forcats=0.5.1=r40hc72bb7e_0
  - r-foreach=1.5.1=r40hc72bb7e_0
  - r-foreign=0.8_81=r40h28b5c78_0
  - r-formatr=1.7=r40h6115d3f_2
  - r-fs=1.5.0=r40h710217c_0
  - r-gdata=2.18.0=r40hc72bb7e_1003
  - r-generics=0.1.0=r40hc72bb7e_0
  - r-ggplot2=3.3.3=r40hc72bb7e_0
  - r-ggrepel=0.9.1=r40h815b84a_0
  - r-gh=1.3.0=r40hc72bb7e_0
  - r-gistr=0.9.0=r40hc72bb7e_0
  - r-git2r=0.28.0=r40h5ea82b1_0
  - r-gitcreds=0.1.1=r40hc72bb7e_0
  - r-glmnet=4.1_2=r40h749f5a1_0
  - r-glue=1.4.2=r40h28b5c78_0
  - r-gmodels=2.18.1=r40ha770c72_1003
  - r-gower=0.2.2=r40h28b5c78_0
  - r-gtable=0.3.0=r40hc72bb7e_3
  - r-gtools=3.8.2=r40h28b5c78_1
  - r-haven=2.3.1=r40hee97c7f_0
  - r-hexbin=1.28.2=r40h749f5a1_0
  - r-highr=0.8=r40h6115d3f_2
  - r-hms=1.0.0=r40hc72bb7e_0
  - r-htmltools=0.5.1.1=r40h815b84a_0
  - r-htmlwidgets=1.5.3=r40hc72bb7e_0
  - r-httpcode=0.3.0=r40h694c41f_1
  - r-httpuv=1.5.5=r40h815b84a_0
  - r-httr=1.4.2=r40hc72bb7e_0
  - r-igraph=1.2.6=r40ha3e3938_1
  - r-ini=0.3.1=r40hc72bb7e_1003
  - r-ipred=0.9_9=r40h17f1fa6_2
  - r-ips=0.0.11=r40hc72bb7e_1
  - r-irdisplay=1.0=r40hd8ed1ab_0
  - r-irkernel=1.1.1=r40h6115d3f_0
  - r-isoband=0.2.3=r40h1019320_0
  - r-iterators=1.0.13=r40hc72bb7e_0
  - r-jquerylib=0.1.3=r40hc72bb7e_0
  - r-jsonlite=1.7.2=r40h28b5c78_0
  - r-kernsmooth=2.23_18=r40h983bced_0
  - r-knitr=1.31=r40hc72bb7e_0
  - r-labeling=0.4.2=r40hc72bb7e_0
  - r-later=1.1.0.1=r40hc5da6b9_0
  - r-lattice=0.20_41=r40h066c5db_3
  - r-lava=1.6.8.1=r40hc72bb7e_0
  - r-lazyeval=0.2.2=r40h28b5c78_2
  - r-learnbayes=2.15.1=r40hc72bb7e_1002
  - r-lifecycle=0.2.0=r40h6115d3f_1
  - r-lubridate=1.7.9.2=r40h1019320_0
  - r-magick=2.6.0=r40h815b84a_0
  - r-magrittr=2.0.1=r40h28b5c78_1
  - r-maps=3.3.0=r40h28b5c78_1004
  - r-markdown=1.1=r40h28b5c78_1
  - r-mass=7.3_53.1=r40hf6ff476_0
  - r-matrix=1.3_2=r40h9a4b173_0
  - r-memoise=2.0.0=r40hc72bb7e_0
  - r-mgcv=1.8_33=r40h9a4b173_0
  - r-mime=0.10=r40h28b5c78_0
  - r-mnormt=2.0.2=r40h749f5a1_0
  - r-modelmetrics=1.2.2.2=r40hc5da6b9_1
  - r-modelr=0.1.8=r40hc72bb7e_0
  - r-munsell=0.5.0=r40hc72bb7e_1003
  - r-mvtnorm=1.1_1=r40h749f5a1_1
  - r-nlme=3.1_152=r40h749f5a1_0
  - r-nnet=7.3_15=r40h066c5db_0
  - r-numderiv=2016.8_1.1=r40hc72bb7e_3
  - r-openssl=1.4.3=r40ha713f70_0
  - r-patchwork=1.1.1=r40hc72bb7e_0
  - r-pbdzmq=0.3_5=r40h5cc58b7_1
  - r-permute=0.9_5=r40h785f33e_3
  - r-phangorn=2.5.5=r40hc5da6b9_2
  - r-phylobase=0.8.10=r40hc5da6b9_1
  - r-phylotate=1.3=r40hc72bb7e_1
  - r-phytools=0.7_70=r40hc72bb7e_0
  - r-pillar=1.4.7=r40hc72bb7e_0
  - r-pixmap=0.4_12=r40hc72bb7e_0
  - r-pkgbuild=1.2.0=r40hc72bb7e_0
  - r-pkgconfig=2.0.3=r40hc72bb7e_1
  - r-pkgload=1.1.0=r40hc5da6b9_0
  - r-plotrix=3.8_1=r40hc72bb7e_0
  - r-plyr=1.8.6=r40hc5da6b9_1
  - r-praise=1.0.0=r40hc72bb7e_1004
  - r-prettyunits=1.1.1=r40hc72bb7e_1
  - r-proc=1.17.0.1=r40h815b84a_0
  - r-processx=3.4.5=r40he27d7ee_0
  - r-prodlim=2019.11.13=r40hc5da6b9_1
  - r-progress=1.2.2=r40hc72bb7e_2
  - r-promises=1.2.0.1=r40h4efb63e_0
  - r-pryr=0.1.4=r40hc5da6b9_1004
  - r-ps=1.5.0=r40h066c5db_0
  - r-purrr=0.3.4=r40h28b5c78_1
  - r-quadprog=1.5_8=r40he19034d_3
  - r-quantmod=0.4.18=r40hc72bb7e_0
  - r-r6=2.5.0=r40hc72bb7e_0
  - r-randomforest=4.6_14=r40h749f5a1_1004
  - r-rappdirs=0.3.3=r40h28b5c78_0
  - r-raster=3.4_5=r40h7d45411_0
  - r-rbokeh=0.5.1=r40hc72bb7e_0
  - r-rcmdcheck=1.3.3=r40hc72bb7e_3
  - r-rcolorbrewer=1.1_2=r40h785f33e_1003
  - r-rcpp=1.0.6=r40h815b84a_0
  - r-readr=1.4.0=r40h342fd00_0
  - r-readxl=1.3.1=r40hee97c7f_4
  - r-recipes=0.1.15=r40hc72bb7e_0
  - r-recommended=4.0=r40hd8ed1ab_1004
  - r-rematch=1.0.1=r40hc72bb7e_1003
  - r-rematch2=2.1.2=r40hc72bb7e_1
  - r-remotes=2.4.0=r40hc72bb7e_0
  - r-repr=1.1.3=r40h785f33e_0
  - r-reprex=1.0.0=r40hc72bb7e_0
  - r-reshape2=1.4.4=r40hc5da6b9_1
  - r-rex=1.2.0=r40hc72bb7e_1
  - r-rlang=0.4.10=r40h066c5db_0
  - r-rmarkdown=2.6=r40hc72bb7e_0
  - r-rncl=0.8.4=r40h4a8c4bd_1
  - r-rnexml=2.4.5=r40hc72bb7e_0
  - r-roxygen2=7.1.1=r40hc5da6b9_0
  - r-rpart=4.1_15=r40h28b5c78_2
  - r-rprojroot=2.0.2=r40hc72bb7e_0
  - r-rstudioapi=0.13=r40hc72bb7e_0
  - r-rvcheck=0.1.8=r40hc72bb7e_1
  - r-rversions=2.1.1=r40hc72bb7e_0
  - r-rvest=0.3.6=r40h6115d3f_0
  - r-sass=0.3.1=r40h815b84a_0
  - r-scales=1.1.1=r40hc72bb7e_0
  - r-scatterplot3d=0.3_41=r40hc72bb7e_1003
  - r-segmented=1.3_2=r40hc72bb7e_0
  - r-selectr=0.4_2=r40hc72bb7e_1
  - r-seqinr=4.2_5=r40h28b5c78_0
  - r-sessioninfo=1.1.1=r40hc72bb7e_1002
  - r-sf=0.9_7=r40ha65de02_1
  - r-shape=1.4.5=r40_0
  - r-shiny=1.6.0=r40hc72bb7e_0
  - r-sourcetools=0.1.7=r40h4a8c4bd_1002
  - r-sp=1.4_5=r40h28b5c78_0
  - r-spatial=7.3_13=r40h066c5db_0
  - r-spdata=0.3.8=r40hc72bb7e_0
  - r-spdep=1.1_5=r40h39f91c9_0
  - r-squarem=2021.1=r40hc72bb7e_0
  - r-stringi=1.5.3=r40h9aeca8d_1
  - r-stringr=1.4.0=r40hc72bb7e_2
  - r-survival=3.2_7=r40hf6ff476_0
  - r-sys=3.4=r40h28b5c78_0
  - r-testthat=3.0.2=r40h4efb63e_0
  - r-tibble=3.0.6=r40hf6ff476_0
  - r-tidyr=1.1.2=r40h710217c_0
  - r-tidyselect=1.1.0=r40h6115d3f_0
  - r-tidytree=0.3.3=r40h6115d3f_1
  - r-tidyverse=1.3.0=r40h6115d3f_2
  - r-timedate=3043.102=r40hc72bb7e_1002
  - r-tinytex=0.29=r40hc72bb7e_0
  - r-tmvnsim=1.0_2=r40h749f5a1_3
  - r-triebeard=0.3.0=r40hb1e8313_1003
  - r-ttr=0.24.2=r40h28b5c78_0
  - r-units=0.7_0=r40h9951f98_0
  - r-urltools=1.7.3=r40h710217c_2
  - r-usethis=1.6.3=r40h6115d3f_0
  - r-utf8=1.1.4=r40h17f1fa6_1003
  - r-uuid=0.1_4=r40h28b5c78_1
  - r-vctrs=0.3.6=r40h066c5db_0
  - r-vegan=2.5_7=r40h30cbcce_0
  - r-viridislite=0.3.0=r40h6115d3f_1003
  - r-waldo=0.2.4=r40hc72bb7e_0
  - r-whisker=0.4=r40hc72bb7e_1
  - r-withr=2.4.1=r40hc72bb7e_0
  - r-xfun=0.20=r40h066c5db_0
  - r-xml=3.99_0.5=r40h066c5db_0
  - r-xml2=1.3.2=r40hc5da6b9_1
  - r-xopen=1.0.0=r40hc72bb7e_1003
  - r-xtable=1.8_4=r40hc72bb7e_3
  - r-xts=0.12.1=r40h28b5c78_0
  - r-yaml=2.2.1=r40h28b5c78_1
  - r-zeallot=0.1.0=r40hc72bb7e_1002
  - r-zoo=1.8_8=r40h17f1fa6_0
  - raxml=8.2.12=hb4d813b_3
  - readline=8.0=h0678c8f_2
  - scipy=1.6.0=py38ha68b950_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h50d1736_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h17101e1_0
  - tapi=1100.0.11=h9ce4665_0
  - terminado=0.9.2=py38h50d1736_0
  - testpath=0.4.4=py_0
  - tiledb=2.2.4=hddf8d7a_1
  - tk=8.6.10=h0419947_1
  - tktable=2.10=h49f0cf7_3
  - tornado=6.1=py38h5406a74_1
  - traitlets=5.0.5=py_0
  - treetime=0.8.1=pyh3252c3a_0
  - tzcode=2021a=h0d85af4_1
  - tzdata=2021a=he74cb21_0
  - udunits2=2.2.27.27=h436e77e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - x264=1!161.3030=h0d85af4_1
  - xerces-c=3.2.3=hd3a8c1e_2
  - xorg-kbproto=1.0.7=h35c211d_1002
  - xorg-libice=1.0.10=h0d85af4_0
  - xorg-libsm=1.2.3=h0d85af4_1000
  - xorg-libx11=1.6.12=h9a43bea_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xorg-libxext=1.3.4=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-libxt=1.2.1=h35c211d_0
  - xorg-renderproto=0.11.1=h0d85af4_1002
  - xorg-xextproto=7.3.0=h35c211d_1002
  - xorg-xproto=7.0.31=h35c211d_1007
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.8=hf387650_1
prefix: /Users/kathryncampbell/miniconda3/envs/MADDOG
